name: TomoSwin3D
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.9
  - pip

  # ML / model
  - pytorch
  - pytorch-cuda=12.4  # remove this line for CPU-only installs

  # Scientific stack
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - tqdm

  # CryoET / IO
  - mrcfile

  # Model components + experiment logging
  - einops
  - timm
  - wandb
